apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-camel-rest
  namespace: openshift-gitops
spec:
  destination:
    namespace: rest-camel-stage
    server: https://kubernetes.default.svc
  project: camel-rest
  source:
    path: environments/stage
    repoURL: https://github.com/erkerc/camel-gitops-demo.git
    targetRevision: HEAD